### ISSUE TITLE
I can't upload WebM's 

### ISSUE THREAD

**Issue by Misunako** [MrBn100ful/fikaba-neonroot#3]
## Describe the bug
I can't upload WebM's. When I try to upload this, I'll always get an error "Can't find record". 

## To Reproduce
1. Go to 'http://satsuma-channel.ga/b/'
2. Try to upload webm
3. See error

## Client :
 - OS: Windows 8.1
 - Browser: Opera

## Server (please complete the following information):
- OS: debian
- Server: apache
- SQL server: mariadb, mysql
- Fikaba version: [e.g. 181008]
- Hosting: 000webhost

**Comment by MrBn100ful** [comment]
What version of php are you using ?

**Comment by Misunako** [comment]
it's 7.3.12

**Comment by MrBn100ful** [comment]
Can you give a copy of your string ( text msg) ?

**Comment by MrBn100ful** [comment]
I think i have found the issue, to upload a webm file on need to have the fonction 'escapeshellarg' enabled.
It look like that free hosting disable it.
Maybe try to upgrade your plan.

**Comment by Misunako** [comment]
Ok, thank you!
Some day I will buy full hosting and I think it will gonna works
